### ISSUE TITLE
The build fails for non-K64F and non-STM32 targets

### ISSUE THREAD

**Issue by Patater** [ARMmbed/uvisor-helloworld#46] opened 2016-01-06 15:30 UTC
When you attempt to build for targets that aren't TARGET_LIKE_FRDM_K64F, and aren't TARGET_LIKE_STM32F429I_DISCO, the following error is generated and the build fails.

```
        source/btn.cpp: In function 'void btn_init()':
        source/btn.cpp:39:27: error: no matching function for call to 'mbed::InterruptIn::mode(PinName)'
             btn.mode(MAIN_BTN_PUPD);
                                   ^
        source/btn.cpp:39:27: note: candidate is:
        In file included from yotta_modules/mbed-drivers/mbed-drivers/mbed.h:59:0,
                         from source/btn.cpp:17:
        yotta_modules/mbed-drivers/mbed-drivers/InterruptIn.h:109:10: note: void mbed::InterruptIn::mode(PinMode)
             void mode(PinMode pull);
                  ^
        yotta_modules/mbed-drivers/mbed-drivers/InterruptIn.h:109:10: note:   no known conversion for argument 1 from 'PinName' to 'PinMode'
```
    
The reason for this is because `NC` is defined as a `PinName`, not a `PinMode`. However, if you replace `NC` with a `PinMode`, a different error is generated and the build still fails.

```
    source/main.cpp:33:24: error: no matching function for call to 'mbed::DigitalOut::DigitalOut(PinMode)'
     DigitalOut led(MAIN_LED);
                            ^
    source/main.cpp:33:24: note: candidates are:
    In file included from yotta_modules/mbed-drivers/mbed-drivers/mbed.h:39:0,
                     from source/main.cpp:17:
    yotta_modules/mbed-drivers/mbed-drivers/DigitalOut.h:57:5: note: mbed::DigitalOut::DigitalOut(PinName, int)
         DigitalOut(PinName pin, int value) : gpio() {
         ^
    yotta_modules/mbed-drivers/mbed-drivers/DigitalOut.h:57:5: note:   candidate expects 2 arguments, 1 provided
    yotta_modules/mbed-drivers/mbed-drivers/DigitalOut.h:48:5: note: mbed::DigitalOut::DigitalOut(PinName)
         DigitalOut(PinName pin) : gpio() {
         ^
    yotta_modules/mbed-drivers/mbed-drivers/DigitalOut.h:48:5: note:   no known conversion for argument 1 from 'PinMode' to 'PinName'
    yotta_modules/mbed-drivers/mbed-drivers/DigitalOut.h:41:7: note: mbed::DigitalOut::DigitalOut(const mbed::DigitalOut&)
     class DigitalOut {
           ^
    yotta_modules/mbed-drivers/mbed-drivers/DigitalOut.h:41:7: note:   no known conversion for argument 1 from 'PinMode' to 'const mbed::DigitalOut&'

```

**Comment by ciarmcom** [comment] 2016-01-06 20:21
ARM Internal Ref: IOTSFW-1702

**Comment by AlessandroA** [comment] 2016-01-25 14:02
@Patater Which target did you use for this? I tried to reproduce the second error you mentioned but got a successful compilation (after changing `NC` to `PullDown`)

**Comment by Patater** [comment] 2016-01-25 15:20
I was attempting to target NRF51.

**Comment by AlessandroA** [comment] 2016-01-25 15:36
I just tried building with the mkit-gcc target (which is an NRF51 target) and it does not show the error. It could be that it was not related to the pre-processor macros and has been fixed since then. I am sending the fix for the `PinMode`. Could you please test it as well?

**Comment by Patater** [comment] 2016-01-25 15:38
Does your fix work for nrf51dk-gcc?

**Comment by AlessandroA** [comment] 2016-01-25 15:39
Yes it builds fine

**Comment by AlessandroA** [comment] 2016-01-25 15:39
(actually wait, I tested on nordic-nrf51822-gcc)

**Comment by Patater** [comment] 2016-01-25 16:02
Super.

**Comment by AlessandroA** [comment] 2016-01-25 16:17
Fixed in https://github.com/ARMmbed/uvisor-helloworld/pull/50

**Closed by AlessandroA** 2016-01-25 16:17 UTC
Labels: bug, mirrored
